# Site settings
name: Nguyễn Nhật Minh
email: nguyenhatminhvip99@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, C++, Kotlin, Data Structures and Algorithms, "
skills: "3rd years students at University of Engineering and Technology - Vietnam National University Hanoi"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/minh-nguyen-nhat-721465196/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100008635754047
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
